name: Deploy to Salesforce

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Salesforce CLI
      run: |
        sudo npm install -g sfdx-cli
        sfdx --version

    - name: Authenticate Salesforce Org
      env:
        SF_USERNAME: ${{ secrets.SF_SANDBOX_USERNAME }}
        SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
        SF_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
        SF_LOGIN_URL: https://login.salesforce.com  # Use https://login.salesforce.com for production
      run: |
        echo "$SF_PRIVATE_KEY" > new.key
        sfdx force:auth:jwt:grant --clientid 3MVG9GCMQoQ6rpzSYFxU9jorNOMhzGLa9QoMfTQfnLwz77FToU9mF9LDyuS.43RsclW_.NnYmApQWofZpbS80 --jwtkeyfile new.key --username kamalgit@cube84.com --instanceurl https://login.salesforce.com
    - name: Deploy to Salesforce
      env:
        SF_SANDBOX_USERNAME: ${{ secrets.SF_SANDBOX_USERNAME }}
      run: |
        sfdx force:source:deploy -p force-app -u ${{ secrets.SF_SANDBOX_USERNAME }} --json --loglevel debug > deploy.log
